# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
env:
  DOCKER_REGISTRY: "docker.elastic.co"
  SETUP_GVM_VERSION: 'v0.5.0' # https://github.com/andrewkroh/gvm/issues/44#issuecomment-1013231151
  SETUP_MAGE_VERSION: '1.14.0'
  # this is required in order to allow the build process to override the default PWD of the BEAT_NAME.
  BEAT_NAME: "elastic-agent"
  # after moving elastic-agent out of beats, we should update the URL of the packaging.
  BEAT_URL: "https://www.elastic.co/elastic-agent"

steps:
  - input: "Build parameters"
    if: build.env("ManifestURL") == null
    fields:
      - text: "ManifestURL"
        key: "ManifestURL"
        default: ""
        required: true
        hint: "Link to the build manifest URL."
      - select: "DEV"
        key: "DEV"
        required: "true"
        options:
          - label: "True"
            value: "true"
          - label: "False"
            value: "false"
        hint: "If DEV=true should be set or the packaging is done with DEV=false"
      - select: "Mage verbose"
        key: "MAGEFILE_VERBOSE"
        required: "false"
        options:
          - label: "True"
            value: "1"
          - label: "False"
            value: "0"
        hint: "Increase verbosity of the mage commands, defaults to 0"
      - select: "DRA DRY-RUN"
        key: "DRA_DRY_RUN"
        required: "false"
        options:
          - label: "True"
            value: "--dry-run"
          - label: "False"
            value: ""
        hint: "If the DRA release manager script would actually publish anything or just print"

  - wait: ~
    if: build.env("ManifestURL") == null

  - label: ":package: Package elastic-agent"
    key: package_elastic-agent
    agents:
      provider: "aws"
      image: "core-ubuntu-2204-aarch64"
    command: |
      if [[ -z "${DEV}" ]]; then
        export DEV=$(buildkite-agent meta-data get DEV --default "true")
      fi
      if [[ -z "${ManifestURL}" ]]; then
        export ManifestURL=$(buildkite-agent meta-data get ManifestURL --default "")
        if [[ -z "${ManifestURL}" ]]; then
          echo ":broken_heart: Missing ManifestURL variable or empty string provided"
          exit 1
        fi
      fi
      if [[ -z "${MAGEFILE_VERBOSE}" ]]; then
        export MAGEFILE_VERBOSE=$(buildkite-agent meta-data get MAGEFILE_VERBOSE --default "0")
      fi
      .buildkite/scripts/steps/package.sh
    artifact_paths:
      - "build/distributions/**/*"

  - label: ":elastic-stack: Publishing to DRA"
    key: dra-publish
    depends_on: package_elastic-agent
    agents:
      provider: "gcp"
      machineType: "c2-standard-16"
    env:
      DRA_PROJECT_ID: "elastic-agent-package"
      DRA_PROJECT_ARTIFACT_ID: "agent-package"
    command: |
      echo "+++ Restoring Artifacts"
      buildkite-agent artifact download "build/**/*" .
      echo "+++ Running DRA publish step"
      if [[ -z "${MAGEFILE_VERBOSE}" ]]; then
        export MAGEFILE_VERBOSE=$(buildkite-agent meta-data get MAGEFILE_VERBOSE --default "0")
      fi
      if [[ -z "${DRA_DRY_RUN}" ]]; then
        DRA_DRY_RUN=$(buildkite-agent meta-data get DRA_DRY_RUN --default "--dry-run")
        export DRA_DRY_RUN
      fi
      if [[ -z "${DRA_VERSION}" ]]; then
        DRA_VERSION=$(curl -s -XGET "${ManifestURL}" |jq '.version' -r | sed 's/-.*//')
        export DRA_VERSION
      fi
      if [[ -z "${DRA_COMMIT}" ]]; then
        DRA_COMMIT=$BUILDKITE_COMMIT
        export DRA_COMMIT
      fi
      if [[ -z "${DRA_BRANCH}" ]]; then
        DRA_BRANCH=$BUILDKITE_BRANCH
        export DRA_BRANCH
      fi
      .buildkite/scripts/steps/dra-publish.sh
